terraform_flavors:
  m1.tiny:
    ram: 512
    vcpus: 1
    disk: 1
  m1.small:
    ram: 2048
    vcpus: 1
    disk: 20
  m1.medium:
    ram: 4096
    vcpus: 2
    disk: 40
  m1.large:
    ram: 8192
    vcpus: 4
    disk: 80
  m1.xlarge:
    ram: 16384
    vcpus: 8
    disk: 160
